export const summerClimateEditorialDraft = {
  editorial_payload: {
    books: [
      {
        author: '옥타비아 E. 버틀러',
        cover: {
          alt: '옥타비아 E. 버틀러의 소설 씨앗을 뿌리는 사람의 우화 한국어판 표지',
          rights_note: 'SF 탐사단의 Aladin Open API ISBN 조회 응답에서 제공된 표지 URL입니다. 이미지를 로컬에 복제하지 않고 원격 표시합니다.',
          rights_status: 'API_LICENSED',
          source_url: 'https://www.aladin.co.kr/shop/wproduct.aspx?ItemId=292291057&partner=openAPI&start=api',
          url: 'https://image.aladin.co.kr/product/29229/10/coversum/8934921579_2.jpg',
        },
        isbn13: '9788934921578',
        position: 1,
        reason: '이 소설은 기후 재난을 거대한 풍경으로만 보여주지 않습니다. 재난이 집값과 일자리, 치안, 약값 같은 일상의 조건을 어떻게 무너뜨리는지부터 살핍니다. 그래서 로런의 여정에서 가장 오래 남는 것은 생존 기술보다 사람을 믿는 방식입니다. 누구와 길을 걷고, 가진 것을 어디까지 나누며, 서로 다른 믿음을 어떻게 견딜 것인지가 매번 문제가 됩니다.',
        reflection: '읽는 동안 자꾸 현재의 뉴스가 겹쳐 보입니다. 그렇다고 예언이 적중했다는 말로만 치켜세우고 싶지는 않습니다. 버틀러가 날카롭게 본 것은 재난의 모양보다 재난이 약한 사람에게 먼저 도착하는 순서였기 때문입니다. 여름의 더위를 견디며 이 책을 읽는 일은, 위기가 왔을 때 내가 지키고 싶은 공동체의 크기를 가늠해 보는 일이기도 합니다.',
        standing: '1993년에 발표된 이 작품은 기후 변화와 사회 붕괴를 함께 다룬 대표적인 미국 SF로 꾸준히 읽혀 왔습니다. 옥타비아 E. 버틀러는 인종, 젠더, 권력, 생존을 장르의 중심 질문으로 가져온 작가입니다. 이 책에서도 파국의 원인을 하나로 단순화하지 않고 기후, 경제적 불평등, 종교, 폭력이 서로를 밀어 올리는 과정을 보여줍니다.',
        synopsis: '기후 변화와 경제 붕괴가 겹친 2024년의 미국. 열다섯 살 로런은 높은 벽으로 둘러싸인 마을에서 가족과 살아갑니다. 타인의 고통을 자신의 몸으로 느끼는 로런은 바깥세상의 위험을 누구보다 예민하게 알아차립니다. 벽이 더는 사람들을 지켜주지 못하게 된 뒤, 로런은 북쪽으로 향하는 길에서 낯선 이들과 작은 공동체를 만들어 갑니다.',
        title: '씨앗을 뿌리는 사람의 우화',
        translator: '장성주',
      },
      {
        author: '엠미 이타란타',
        cover: {
          alt: '엠미 이타란타의 소설 물의 기억 한국어판 표지',
          rights_note: 'SF 탐사단의 Aladin Open API ISBN 조회 응답에서 제공된 표지 URL입니다. 이미지를 로컬에 복제하지 않고 원격 표시합니다.',
          rights_status: 'API_LICENSED',
          source_url: 'https://www.aladin.co.kr/shop/wproduct.aspx?ItemId=114712333&partner=openAPI&start=api',
          url: 'https://image.aladin.co.kr/product/11471/23/coversum/k962531103_1.jpg',
        },
        isbn13: '9791157233267',
        position: 2,
        reason: '세 권 가운데 가장 조용한 책입니다. 하지만 물 한 통을 배급받기 위해 줄을 서는 일, 친구에게 물을 나눠 주는 일, 차 한 잔을 정성껏 내리는 일이 모두 정치적인 선택이 됩니다. 물이 부족하다는 설정을 설명하는 데 머물지 않고, 누가 물을 소유하고 누가 사용을 허락받는지 묻기 때문입니다.',
        reflection: '노리아가 차를 우리며 물의 온도와 소리에 귀를 기울이는 장면들은 빠르게 읽고 지나가기 어렵습니다. 수도꼭지를 틀면 물이 나오는 생활이 얼마나 많은 약속 위에 놓여 있는지 생각하게 합니다. 거창한 영웅담보다 사소한 습관과 우정이 세계를 기억하는 방법일 수 있다는 점도 좋았습니다. 뜨거운 날 천천히 읽기에 어울리는 책입니다.',
        standing: '핀란드 작가 엠미 이타란타의 첫 장편으로, 아서 C. 클라크상과 필립 K. 딕상 후보에 올랐습니다. 청소년 소설의 성장 서사와 기후 SF의 문제의식을 함께 품고 있습니다. 북유럽의 차가운 풍경과 차 의식이라는 낯선 조합 덕분에, 물 부족을 다룬 다른 디스토피아와도 결이 다릅니다.',
        synopsis: '기후가 바뀌고 바닷물이 육지를 삼킨 먼 미래의 북유럽. 깨끗한 물은 군이 통제하는 귀한 자원이 되었습니다. 열일곱 살 노리아는 아버지에게서 차 장인의 일을 배우며, 집안이 여러 세대에 걸쳐 지켜 온 비밀을 알게 됩니다. 이웃의 물이 말라 가는 가운데 노리아는 가족의 약속과 목마른 사람들 사이에서 선택해야 합니다.',
        title: '물의 기억',
        translator: '현혜진',
      },
      {
        author: '마거릿 애트우드',
        cover: {
          alt: '마거릿 애트우드의 소설 오릭스와 크레이크 한국어판 표지',
          rights_note: 'SF 탐사단의 Aladin Open API ISBN 조회 응답에서 제공된 표지 URL입니다. 이미지를 로컬에 복제하지 않고 원격 표시합니다.',
          rights_status: 'API_LICENSED',
          source_url: 'https://www.aladin.co.kr/shop/wproduct.aspx?ItemId=211671056&partner=openAPI&start=api',
          url: 'https://image.aladin.co.kr/product/21167/10/coversum/8937454548_1.jpg',
        },
        isbn13: '9788937454547',
        position: 3,
        reason: '앞의 두 작품이 공동체와 자원의 문제를 가까이서 바라본다면, 이 책은 파국을 만들어 내는 산업 전체를 해부합니다. 더 많은 소비를 위해 동물과 인간의 몸을 설계하고, 불안을 치료한다며 다시 상품을 내놓는 세계입니다. 기술이 놀라울수록 그것을 누가 소유하고 어떤 욕망에 쓰는지 물어야 한다는 사실을 집요하게 보여줍니다.',
        reflection: '이 책에는 우스워서 웃었다가 곧 불편해지는 순간이 많습니다. 기괴한 신제품 이름과 광고 문구가 과장처럼 보이지 않는 탓입니다. 읽고 나면 크레이크 한 사람의 오만보다 그런 선택을 매일 보상한 시스템을 더 오래 생각하게 됩니다. 세 권의 마지막에 놓은 이유도 여기에 있습니다. 지키고 싶은 것을 말하려면 무엇이 그것을 망가뜨리는지도 봐야 합니다.',
        standing: '2003년 부커상 최종 후보에 오른 작품이며, 애트우드의 매드애덤 삼부작을 여는 소설입니다. 기후 변화, 대량 멸종, 유전자 조작, 제약 산업을 한 세계 안에 묶어 21세기 생태·기술 디스토피아의 중요한 기준점이 되었습니다. 과학기술 자체보다 기술을 움직이는 자본과 욕망을 겨눈다는 점에서 지금도 읽을 이유가 선명합니다.',
        synopsis: '스노우맨은 문명이 무너진 뒤 낯선 신인류와 함께 살아가는 마지막 인간처럼 보입니다. 그는 지미라는 이름으로 살던 시절, 뛰어난 과학자 크레이크와 수수께끼 같은 오릭스를 만났던 과거를 되짚습니다. 거대 생명공학 기업이 사람의 몸과 욕망까지 상품으로 만들던 세계가 어떻게 지금의 폐허에 이르렀는지가 조금씩 드러납니다.',
        title: '오릭스와 크레이크',
        translator: '차은정',
      },
    ],
    closing: '세 작품의 미래는 서로 다릅니다. 한쪽에서는 사람들이 길 위에서 공동체를 만들고, 다른 쪽에서는 차 한 잔에 필요한 물을 지키며, 또 다른 쪽에서는 생명을 설계한 기술이 세계를 되돌릴 수 없는 곳으로 밀어붙입니다. 공통점은 기후 위기가 날씨만의 문제가 아니라는 데 있습니다. 누구와 살 것인지, 한정된 것을 어떻게 나눌 것인지, 만들 수 있다는 이유만으로 만들어도 되는지를 함께 묻습니다. 이번 여름에는 세 권을 서둘러 정복하기보다 한 권씩 천천히 읽어 보셔도 좋겠습니다. 더위가 조금 가신 뒤에도 질문은 오래 남을 테니까요.',
    deck: '불타는 길, 감춰진 샘, 설계된 생명. 세 편의 소설이 기후 위기 속에서 우리가 지키려는 것을 서로 다른 거리에서 바라봅니다.',
    intro: '폭염이 길어질수록 기후 위기는 너무 크고 익숙한 말이 됩니다. 숫자는 심각한데, 막상 오늘 무엇을 생각해야 할지는 흐릿해지기도 하지요. 소설은 그 거리를 좁혀 줍니다. 집을 떠나야 하는 사람의 발바닥, 누군가에게 건네는 물 한 잔, 실험실에서 새로 설계된 생명의 몸으로 위기를 만지게 합니다. 이번 편집 추천은 같은 재난을 되풀이하는 책 세 권이 아닙니다. 공동체, 물, 생명이라는 서로 다른 자리에서 기후 위기를 바라보는 작품을 골랐습니다.',
    sources: [
      { book_isbn13: '9788934921578', label: '김영사 한국어판 도서 정보', type: 'PUBLISHER', url: 'https://www.gimmyoung.com/book/books/view/book/5254' },
      { book_isbn13: '9788934921578', label: '교보문고 한국어판 서지', type: 'BOOKSELLER', url: 'https://product.kyobobook.co.kr/detail/S000000594128' },
      { book_isbn13: '9788934921578', label: 'Stories for Earth 기후 SF 입문 영상', type: 'YOUTUBE', url: 'https://www.youtube.com/watch?v=8q_RsA6sxIo' },
      { book_isbn13: '9788934921578', label: 'Crash Course Literature 작품 해설', type: 'YOUTUBE', url: 'https://www.youtube.com/watch?v=6iVGuMyKFgA' },
      { book_isbn13: '9788934921578', label: '기후 위기와 돌봄 공동체 국내 연구', type: 'ACADEMIC', url: 'https://doi.org/10.46349/kjhss.2024.06.48.2.95' },
      { book_isbn13: '9791157233267', label: '교보문고 한국어판 서지', type: 'BOOKSELLER', url: 'https://product.kyobobook.co.kr/detail/S000001752371' },
      { book_isbn13: '9791157233267', label: '작가 공식 작품·수상 정보', type: 'AUTHOR', url: 'https://www.emmiitaranta.com/en/books/memory-of-water/' },
      { book_isbn13: '9791157233267', label: 'Strange Horizons 비평', type: 'REVIEW', url: 'https://strangehorizons.com/wordpress/non-fiction/reviews/memory-of-water-by-emmi-itaranta/' },
      { book_isbn13: '9791157233267', label: 'Reactor 작품 비평', type: 'REVIEW', url: 'https://reactormag.com/book-review-a-memory-of-water-emmi-itaranta/' },
      { book_isbn13: '9791157233267', label: 'Memory of Water 영상 서평', type: 'YOUTUBE', url: 'https://www.youtube.com/watch?v=zSnLrssLTwo' },
      { book_isbn13: '9788937454547', label: '민음사 한국어판 도서 정보', type: 'PUBLISHER', url: 'https://minumsa.minumsa.com/book/16880/' },
      { book_isbn13: '9788937454547', label: '교보문고 한국어판 서지', type: 'BOOKSELLER', url: 'https://product.kyobobook.co.kr/detail/S000000620097' },
      { book_isbn13: '9788937454547', label: 'Booker Prize 공식 작품 정보', type: 'AWARD', url: 'https://thebookerprizes.com/the-booker-library/books/oryx-and-crake' },
      { book_isbn13: '9788937454547', label: 'Kirkus 작품 비평', type: 'REVIEW', url: 'https://www.kirkusreviews.com/book-reviews/margaret-atwood/oryx-and-crake/' },
      { book_isbn13: '9788937454547', label: 'Oryx and Crake 영상 서평', type: 'YOUTUBE', url: 'https://www.youtube.com/watch?v=DNKIepENzko' },
      { book_isbn13: null, label: 'Reddit r/printSF 기후 디스토피아 추천 논의', type: 'COMMUNITY', url: 'https://www.reddit.com/r/printSF/comments/1rh76fe/recommend_me_a_dystopia_novel_covering_all_the/' },
    ],
    theme: '한여름의 기후 SF — 무너지는 세계에서 우리가 지키려는 것들',
  },
  editorial_stage: 'REVIEW_READY',
  image_alt: '',
  image_url: '',
  internal_notes: '선정 승인 hash: sha256:50b5f1f70225f6481b7e13fa2c6db5f5426a62c594c41f24b2bc1ee50665ef84. 발췌문은 한국어판 페이지 미대조로 제외. 표지는 Aladin Open API 응답 URL을 원격 표시하며 로컬에 저장하지 않음. 보라 최종 검수 전 발행 금지.',
  is_spoiler: false,
  kind: 'EDITOR_PICK',
  media_type: 'NOVEL',
  publication_status: 'DRAFT',
  release_date: '',
  selection_approval_ref: 'sha256:50b5f1f70225f6481b7e13fa2c6db5f5426a62c594c41f24b2bc1ee50665ef84',
  selection_approved_at: '2026-08-06T05:16:36Z',
  slug: 'summer-climate-sf-what-we-keep',
  sort_priority: 100,
  source_name: 'SF 탐사단 편집부 검증 출처 16건',
  source_url: 'https://www.gimmyoung.com/book/books/view/book/5254',
  summary: '불타는 길, 감춰진 샘, 설계된 생명. 《씨앗을 뿌리는 사람의 우화》, 《물의 기억》, 《오릭스와 크레이크》가 기후 위기 속에서 우리가 지키려는 것을 묻습니다.',
  title: '한여름의 기후 SF: 우리가 지키려는 것들',
};
